package adobe:cai@0.1.0;

world cai {
    export c2pa;
    export types;

    import c2pa-signer;
}

world signer {
    import types;
    export c2pa-signer;
}

world c2pa-tool {
    import c2pa;
}

world c2pa-webserver {
    import c2pa;
    export wasi:http/incoming-handler@0.2.2;
}

interface c2pa-signer {
    use types.{error};
    sign: func(data: list<u8>) -> result<list<u8>, error>;
}

interface c2pa {
    use wasi:io/streams@0.2.2.{input-stream, output-stream};
    use types.{assertion-type, error, input, manifest-definition, output, signer-config, signing-algorithm};


    format-from-path: func(path: string) -> option<string>;

    resource builder {
        constructor(json: option<string>);
        set-remote-url: func(url: string);
        set-no-embed: func(embed: bool);
        add-assertion: func(label: string, assertion: string, kind:option<assertion-type>) -> result<_, error>;
        add-ingredient: func(ingredient-json: string, format: string, %stream: input) -> result<_, error>;
        add-resource: func(uri: string, %stream: input) -> result<_, error>;
        to-archive: func(%stream: output) -> result<_, error>;
        from-archive: static func(%stream: input) -> result<builder, error>;
        sign: func(config: signer-config, format: string, source: input, dest: output) -> result<list<u8>, error>;
    }

    resource reader {
        constructor(json: option<string>);
        from-buffer: static func(format: string, buf: list<u8>) -> result<reader, error>;
        from-stream: static func(format: string, %stream: input) -> result<reader, error>;
        from-manifest-data-and-stream: static func(manifest-data: list<u8>, format: string, %stream: input) -> result<reader, error>;
        json: func() -> string;
        resource-to-stream: func(uri: string, %stream: output) -> result<u64, error>;
        active-manifest: func() -> option<manifest-definition>;
    }
}
