[package]
name = "c2pa-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
c2pa = { git = "https://github.com/contentauth/c2pa-rs.git", branch = "main", features = ["file_io"]}
pem = "3.0.4"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.103", features = ["arbitrary_precision"] }
tempfile = "=3.15.0"
wasi = "0.14.1"
wit-bindgen = { version = "0.39", features = ["default"] }

[package.metadata.component.target]
path = "../wit"
world = "cai"

[package.metadata.component.target.dependencies]
"wasi:io" = { path = "../wit/deps/io" }
